### ISSUE TITLE
Bug? Broken compatibility with grpc-java client version > 1.0.1 

### ISSUE THREAD

**Issue by yfinkelstein** [grpc-ecosystem/grpc-opentracing#15] opened 2017-02-22 09:01 UTC
grpc-java versions newer than 1.0.1 have a binary header **_grpc-census-bin_** being sent with every request from client to server:
https://github.com/grpc/grpc-java/blob/6ff5f2149bb643fa6cc951e42831c067003ff810/core/src/main/java/io/grpc/internal/StatsTraceContext.java#L154

I believe there is a bug on this line:
https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/java/src/main/java/io/opentracing/contrib/ServerTracingInterceptor.java#L86
in that it assumes that all headers are ascii and blows with this exception:

> java.lang.IllegalArgumentException: ASCII header is named grpc-census-bin.  Only binary headers may end with -bin
>at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
>at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:742)
>at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:736)
>at io.grpc.Metadata$Key.of(Metadata.java:594)
>at io.opentracing.contrib.grpc.ServerTracingInterceptor.interceptCall(ServerTracingInterceptor.java:87)
>at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)

**Comment by yfinkelstein** [comment] 2017-02-22 09:06
Basically, this makes grpc-opentracing incompatible with all java grpc clients newer than 1.0.1. I wonder how come nobody has noticed?

**Comment by bhs** [comment] 2017-02-22 17:39
@yfinkelstein since you are able to reproduce this easily, want to just fix it by adding the necessary defensive (try/catch) code at line 86? I'm happy to review the PR.

**Comment by yfinkelstein** [comment] 2017-02-22 17:55
Sure we can do it. Since the issue is with newer versions of GRPC, do you mind of we upgrade the build spec with the latest available versions of all dependencies (grpc, protobuf, etc) ?

**Comment by bhs** [comment] 2017-02-22 17:59
@yfinkelstein sure, might as well!

**Comment by hzariv** [comment] 2017-02-24 03:01
@bhs the correct fix is to add support for binary headers. Something like this:

```java
 for (String key : headers.keys()) {
            if (key.endsWith(Metadata.BINARY_HEADER_SUFFIX)) {
                Metadata.Key<byte[]> headerKey = Metadata.Key.of(key, Metadata.BINARY_BYTE_MARSHALLER);
                byte[] byteValue = headers.get(headerKey);
                headerMap.put(headerKey.name(), new String(byteValue));
            } else {
                String value = headers.get(Metadata.Key.of(key, Metadata.ASCII_STRING_MARSHALLER));
                headerMap.put(key, value);
            }

        }
```

**Comment by bhs** [comment] 2017-02-24 04:26
@hzariv, there's possibly a subtle corner-case bug involving charset/encoding assumptions with `byteValue` above. I would be ok merely dropping them and logging an error. (And/or putting something in the README?) Thanks for pointing out BINARY_HEADER_SUFFIX in any case!

**Comment by hzariv** [comment] 2017-02-24 20:41
@bhs I have sent a pull request. This issue is blocking us from upgrading to latest version of gRPC-Java. Thank for your attention.

**Comment by hzariv** [comment] 2017-02-27 16:50
@yfinkelstein updated version 0.2.0 is now available in maven [central](https://search.maven.org/#artifactdetails%7Cio.opentracing.contrib%7Cgrpc-opentracing%7C0.2.0%7Cjar). You can go ahead and close this.

**Closed as completed** 2017-10-26 00:27 UTC
